services:
  mirage:
    image: ghcr.io/gigirassy/mirage:main
    container_name: mirage
    env_file: .env
    ports:
      - "3000:3000" # change first if already taken
    environment:
      - PYTHONUNBUFFERED=1
      - MIRAGE_CACHE_MAX=41943040    # 40 MB
      - MIRAGE_CACHE_TTL=604800      # 7 days
      - MIRAGE_CACHE_KEY=${MIRAGE_CACHE_KEY}
      - USER_AGENT=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0
    volumes:
      - ./cache:/app/cache:rw
    restart: unless-stopped
